/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/api-keys/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET/POST /api/auth/api-keys/ — list and create your own API keys.
         *
         *     The raw key is returned only on creation (never on list).
         */
        get: operations["auth_api_keys_list"];
        put?: never;
        /**
         * @description GET/POST /api/auth/api-keys/ — list and create your own API keys.
         *
         *     The raw key is returned only on creation (never on list).
         */
        post: operations["auth_api_keys_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/api-keys/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/DELETE /api/auth/api-keys/<id>/ — revoke (delete) one of your keys. */
        get: operations["auth_api_keys_retrieve"];
        put?: never;
        post?: never;
        /** @description GET/DELETE /api/auth/api-keys/<id>/ — revoke (delete) one of your keys. */
        delete: operations["auth_api_keys_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/login/ — session-based login (admin / browser). */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/logout/ — end the session. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/auth/me/ — return the currently authenticated user. */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /api/auth/register/ — create a new user account. */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_list"];
        put?: never;
        post: operations["categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_retrieve"];
        put: operations["categories_update"];
        post?: never;
        delete: operations["categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["categories_partial_update"];
        trace?: never;
    };
    "/api/cities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read-only city catalog.
         *
         *     - Search: ``?search=<text>`` matches the city name (prefix/contains).
         *     - Filter: ``?country_code=DE``.
         *     - Order:  ``?ordering=name`` (default) or ``?ordering=-population``.
         *     - Page size: ``?page_size=<n>`` (capped at 1000).
         *     - Full list (no pagination): ``/api/cities/all/`` — returns every active
         *       city in one response, for clients that want to cache the whole catalog
         *       (e.g. an offline pick-list / autocomplete).
         */
        get: operations["cities_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Read-only city catalog.
         *
         *     - Search: ``?search=<text>`` matches the city name (prefix/contains).
         *     - Filter: ``?country_code=DE``.
         *     - Order:  ``?ordering=name`` (default) or ``?ordering=-population``.
         *     - Page size: ``?page_size=<n>`` (capped at 1000).
         *     - Full list (no pagination): ``/api/cities/all/`` — returns every active
         *       city in one response, for clients that want to cache the whole catalog
         *       (e.g. an offline pick-list / autocomplete).
         */
        get: operations["cities_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cities/all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return every active city in a single unpaginated response. */
        get: operations["cities_all_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        get: operations["events_list"];
        put?: never;
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        post: operations["events_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        get: operations["events_retrieve"];
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        put: operations["events_update"];
        post?: never;
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        delete: operations["events_destroy"];
        options?: never;
        head?: never;
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        patch: operations["events_partial_update"];
        trace?: never;
    };
    "/api/events/{id}/archive/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        post: operations["events_archive_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        post: operations["events_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/publish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        post: operations["events_publish_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}/revert_to_draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description List, create, retrieve, update and destroy events.
         *
         *     - Filter: ``?category=<id>&category__slug=<slug>&city=<city>&organization=<id>&
         *       organization_slug=<slug>&event_type=<…>&attendance_mode=<…>&status=<…>&
         *       starts_at_after=&starts_at_before=``
         *     - Search: ``?search=<text>`` matches title and description.
         *     - Order:  ``?ordering=starts_at`` (or ``-starts_at``).
         *     - Proximity: ``?lat=<lat>&lon=<lon>&radius_km=<km>`` (or ``?near_city=<slug>``)
         *       returns events within the radius, each annotated with a ``distance`` (km),
         *       ordered nearest-first. **Online events are excluded** from proximity.
         *     - Lifecycle actions: ``POST /api/events/<id>/publish/``,
         *       ``/cancel/``, ``/archive/``, ``/revert_to_draft/`` (owner / ``owner_group``
         *       member / holder of ``events.change_event``).
         */
        post: operations["events_revert_to_draft_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/observations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Submit and read untrusted event observations.
         *
         *     ``POST`` submits one observation (forced ``status=pending``); ``bulk/``
         *     submits a list transactionally. List/retrieve let the extractor confirm what
         *     it submitted. Reviewing/promoting is an operator action in the admin.
         */
        get: operations["ingestion_observations_list"];
        put?: never;
        /**
         * @description Submit and read untrusted event observations.
         *
         *     ``POST`` submits one observation (forced ``status=pending``); ``bulk/``
         *     submits a list transactionally. List/retrieve let the extractor confirm what
         *     it submitted. Reviewing/promoting is an operator action in the admin.
         */
        post: operations["ingestion_observations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/observations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Submit and read untrusted event observations.
         *
         *     ``POST`` submits one observation (forced ``status=pending``); ``bulk/``
         *     submits a list transactionally. List/retrieve let the extractor confirm what
         *     it submitted. Reviewing/promoting is an operator action in the admin.
         */
        get: operations["ingestion_observations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/observations/bulk/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Submit and read untrusted event observations.
         *
         *     ``POST`` submits one observation (forced ``status=pending``); ``bulk/``
         *     submits a list transactionally. List/retrieve let the extractor confirm what
         *     it submitted. Reviewing/promoting is an operator action in the admin.
         */
        post: operations["ingestion_observations_bulk_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/runs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Report ingestion runs.
         *
         *     ``POST`` creates a run (defaults to ``running``, ``reported_by`` = caller);
         *     ``PATCH`` (or the ``/success/`` / ``/failure/`` actions) finishes it. Finishing
         *     a run also stamps its source's ``last_fetched_at`` / ``next_due_at`` schedule.
         */
        get: operations["ingestion_runs_list"];
        put?: never;
        /**
         * @description Report ingestion runs.
         *
         *     ``POST`` creates a run (defaults to ``running``, ``reported_by`` = caller);
         *     ``PATCH`` (or the ``/success/`` / ``/failure/`` actions) finishes it. Finishing
         *     a run also stamps its source's ``last_fetched_at`` / ``next_due_at`` schedule.
         */
        post: operations["ingestion_runs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/runs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Report ingestion runs.
         *
         *     ``POST`` creates a run (defaults to ``running``, ``reported_by`` = caller);
         *     ``PATCH`` (or the ``/success/`` / ``/failure/`` actions) finishes it. Finishing
         *     a run also stamps its source's ``last_fetched_at`` / ``next_due_at`` schedule.
         */
        get: operations["ingestion_runs_retrieve"];
        /**
         * @description Report ingestion runs.
         *
         *     ``POST`` creates a run (defaults to ``running``, ``reported_by`` = caller);
         *     ``PATCH`` (or the ``/success/`` / ``/failure/`` actions) finishes it. Finishing
         *     a run also stamps its source's ``last_fetched_at`` / ``next_due_at`` schedule.
         */
        put: operations["ingestion_runs_update"];
        post?: never;
        /**
         * @description Report ingestion runs.
         *
         *     ``POST`` creates a run (defaults to ``running``, ``reported_by`` = caller);
         *     ``PATCH`` (or the ``/success/`` / ``/failure/`` actions) finishes it. Finishing
         *     a run also stamps its source's ``last_fetched_at`` / ``next_due_at`` schedule.
         */
        delete: operations["ingestion_runs_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Report ingestion runs.
         *
         *     ``POST`` creates a run (defaults to ``running``, ``reported_by`` = caller);
         *     ``PATCH`` (or the ``/success/`` / ``/failure/`` actions) finishes it. Finishing
         *     a run also stamps its source's ``last_fetched_at`` / ``next_due_at`` schedule.
         */
        patch: operations["ingestion_runs_partial_update"];
        trace?: never;
    };
    "/api/ingestion/runs/{id}/failure/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ``POST /api/ingestion/runs/<id>/failure/`` — mark the run failed. */
        post: operations["ingestion_runs_failure_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/runs/{id}/success/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description ``POST /api/ingestion/runs/<id>/success/`` — mark the run succeeded. */
        post: operations["ingestion_runs_success_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/sources/due/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ``GET /api/ingestion/sources/due/`` — the extractor's work queue.
         *
         *     Approved, active sources due for a fetch, ordered so never-fetched sources
         *     (``next_due_at`` is null) come first, then by soonest due time.
         */
        get: operations["ingestion_sources_due_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Public, read-only organization catalog.
         *
         *     Only active organizations are listed. An organization's events are available
         *     via the ``/events/`` detail action (published only, with proximity support).
         */
        get: operations["organizations_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Public, read-only organization catalog.
         *
         *     Only active organizations are listed. An organization's events are available
         *     via the ``/events/`` detail action (published only, with proximity support).
         */
        get: operations["organizations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{slug}/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Public, read-only organization catalog.
         *
         *     Only active organizations are listed. An organization's events are available
         *     via the ``/events/`` detail action (published only, with proximity support).
         */
        get: operations["organizations_events_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["venues_list"];
        put?: never;
        post: operations["venues_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["venues_retrieve"];
        put: operations["venues_update"];
        post?: never;
        delete: operations["venues_destroy"];
        options?: never;
        head?: never;
        patch: operations["venues_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Read serializer for API keys (never exposes the raw key). */
        APIKey: {
            readonly id: number;
            /** @description Label for this key. */
            name: string;
            /** @description Public prefix to identify the key. */
            readonly prefix: string;
            /** Format: date-time */
            readonly created: string;
            readonly revoked: boolean;
            /** Format: date-time */
            readonly expires_at: string | null;
        };
        /** @description Create serializer; returns the raw key exactly once in ``key``. */
        APIKeyCreate: {
            readonly id: number;
            /** @description Label for this key. */
            name: string;
            /** @description Public prefix to identify the key. */
            readonly prefix: string;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            expires_at?: string | null;
            readonly key: string;
        };
        /** @description Create serializer; returns the raw key exactly once in ``key``. */
        APIKeyCreateRequest: {
            /** @description Label for this key. */
            name: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
        /**
         * @description * `physical` - Physical
         *     * `online` - Online
         *     * `hybrid` - Hybrid
         * @enum {string}
         */
        AttendanceModeEnum: "physical" | "online" | "hybrid";
        Category: {
            readonly id: number;
            name: string;
            readonly slug: string;
        };
        CategoryRequest: {
            name: string;
        };
        /** @description Read-only representation of a city, exposing its centroid as lat/lon. */
        City: {
            readonly id: number;
            /** @description Stable GeoNames id; idempotency key for re-seeding. */
            readonly geoname_id: number | null;
            readonly name: string;
            readonly slug: string;
            readonly country: string;
            readonly country_code: string;
            readonly latitude: string;
            readonly longitude: string;
            /** @description Suggested search radius (km) for ?near_city=. */
            readonly default_radius_km: number;
            readonly population: number | null;
            readonly timezone: string;
        };
        /**
         * @description A source eligible for extraction (approved + active + due).
         *
         *     Read-only; this is the extractor's work queue.
         */
        DueSource: {
            readonly id: number;
            readonly organization: components["schemas"]["_OrganizationMini"];
            /** Format: uri */
            readonly url: string;
            /** @description Where the source lives, e.g. 'meetup', 'eventbrite', 'homepage'. */
            readonly platform: string;
            /** @description How often the extractor should revisit this source. */
            readonly fetch_interval_minutes: number;
            /** Format: date-time */
            readonly last_fetched_at: string | null;
            /** Format: date-time */
            readonly next_due_at: string | null;
        };
        Event: {
            readonly id: number;
            title: string;
            description?: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at?: string | null;
            /** Format: uri */
            readonly hero_image: string;
            readonly venue: components["schemas"]["Venue"];
            readonly organization: components["schemas"]["OrganizationPublic"];
            readonly categories: components["schemas"]["Category"][];
            capacity?: number | null;
            readonly status: components["schemas"]["EventStatusEnum"];
            event_type?: components["schemas"]["EventTypeEnum"];
            attendance_mode?: components["schemas"]["AttendanceModeEnum"];
            /** Format: date-time */
            readonly published_at: string | null;
            /** Format: date-time */
            readonly cancelled_at: string | null;
            /** Format: uri */
            original_url?: string;
            original_platform?: string;
            readonly source: components["schemas"]["EventSourceNested"];
            readonly promoted_from: components["schemas"]["EventObservationNested"];
            readonly created_by: number | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly distance: string;
        };
        /** @description Full read of an observation (listing / admin / retrieval). */
        EventObservation: {
            readonly id: number;
            readonly source: number;
            readonly run: number | null;
            readonly status: components["schemas"]["StatusF3dEnum"];
            readonly title: string;
            readonly description: string;
            /** Format: date-time */
            readonly starts_at: string;
            /** Format: date-time */
            readonly ends_at: string | null;
            /**
             * Format: uri
             * @description Observed original URL.
             */
            readonly url: string;
            /** @description Observed original platform. */
            readonly platform: string;
            readonly attendance_mode: components["schemas"]["AttendanceModeEnum"];
            readonly event_type: components["schemas"]["EventTypeEnum"];
            readonly venue_name: string;
            readonly venue_address: string;
            readonly venue_city: string;
            readonly latitude: string;
            readonly longitude: string;
            readonly reviewed_by: number | null;
            /** Format: date-time */
            readonly reviewed_at: string | null;
            readonly review_note: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Minimal read-only view of an observation, used on ``Event.promoted_from``.
         *
         *     Deliberately small so the canonical-event payload can't recurse into the
         *     full observation graph.
         */
        EventObservationNested: {
            readonly id: number;
            readonly title: string;
            /** Format: date-time */
            readonly starts_at: string;
            /**
             * Format: uri
             * @description Observed original URL.
             */
            readonly url: string;
            /** @description Observed original platform. */
            readonly platform: string;
            readonly status: components["schemas"]["StatusF3dEnum"];
        };
        /**
         * @description The extractor's submit payload for a single observation.
         *
         *     ``source`` is required (which source the observation came from); ``run`` is
         *     optional (set when reporting inside a run). ``status`` is forced to
         *     ``pending`` — the extractor can never self-promote. ``latitude`` /
         *     ``longitude`` are write-only and stored as ``location``.
         */
        EventObservationSubmit: {
            readonly id: number;
            source: number;
            run?: number | null;
            status?: components["schemas"]["StatusF3dEnum"];
            raw_payload?: unknown;
            title: string;
            description?: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at?: string | null;
            /**
             * Format: uri
             * @description Observed original URL.
             */
            url?: string;
            /** @description Observed original platform. */
            platform?: string;
            attendance_mode?: components["schemas"]["AttendanceModeEnum"];
            event_type?: components["schemas"]["EventTypeEnum"];
            venue_name?: string;
            venue_address?: string;
            venue_city?: string;
        };
        /**
         * @description The extractor's submit payload for a single observation.
         *
         *     ``source`` is required (which source the observation came from); ``run`` is
         *     optional (set when reporting inside a run). ``status`` is forced to
         *     ``pending`` — the extractor can never self-promote. ``latitude`` /
         *     ``longitude`` are write-only and stored as ``location``.
         */
        EventObservationSubmitRequest: {
            source: number;
            run?: number | null;
            status?: components["schemas"]["StatusF3dEnum"];
            raw_payload?: unknown;
            title: string;
            description?: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at?: string | null;
            /**
             * Format: uri
             * @description Observed original URL.
             */
            url?: string;
            /** @description Observed original platform. */
            platform?: string;
            attendance_mode?: components["schemas"]["AttendanceModeEnum"];
            event_type?: components["schemas"]["EventTypeEnum"];
            venue_name?: string;
            venue_address?: string;
            venue_city?: string;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        EventRequest: {
            title: string;
            description?: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at?: string | null;
            capacity?: number | null;
            event_type?: components["schemas"]["EventTypeEnum"];
            attendance_mode?: components["schemas"]["AttendanceModeEnum"];
            /** Format: uri */
            original_url?: string;
            original_platform?: string;
            owner_group_id?: number | null;
            category_ids?: number[];
            venue_id?: number | null;
            organization_id?: number | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        /** @description Minimal read-only view of an event source, used on ``Event.source``. */
        EventSourceNested: {
            readonly id: number;
            /** Format: uri */
            readonly url: string;
            /** @description Where the source lives, e.g. 'meetup', 'eventbrite', 'homepage'. */
            readonly platform: string;
        };
        /**
         * @description * `draft` - Draft
         *     * `published` - Published
         *     * `cancelled` - Cancelled
         *     * `archived` - Archived
         * @enum {string}
         */
        EventStatusEnum: "draft" | "published" | "cancelled" | "archived";
        /**
         * @description * `meetup` - Meetup
         *     * `conference` - Conference
         *     * `workshop` - Workshop
         *     * `social` - Social
         *     * `other` - Other
         * @enum {string}
         */
        EventTypeEnum: "meetup" | "conference" | "workshop" | "social" | "other";
        /**
         * @description Report an ingestion run.
         *
         *     On create, ``status`` defaults to ``running`` and ``reported_by`` is set by
         *     the view to the calling service account. The extractor later PATCHes the run
         *     to ``succeeded`` / ``failed`` with ``finished_at`` / ``events_found`` /
         *     ``error_message``.
         */
        IngestionRun: {
            readonly id: number;
            source: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string | null;
            status?: components["schemas"]["IngestionRunStatusEnum"];
            events_found?: number;
            readonly events_promoted: number;
            error_message?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description Report an ingestion run.
         *
         *     On create, ``status`` defaults to ``running`` and ``reported_by`` is set by
         *     the view to the calling service account. The extractor later PATCHes the run
         *     to ``succeeded`` / ``failed`` with ``finished_at`` / ``events_found`` /
         *     ``error_message``.
         */
        IngestionRunRequest: {
            source: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string | null;
            status?: components["schemas"]["IngestionRunStatusEnum"];
            events_found?: number;
            error_message?: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `running` - Running
         *     * `succeeded` - Succeeded
         *     * `failed` - Failed
         * @enum {string}
         */
        IngestionRunStatusEnum: "pending" | "running" | "succeeded" | "failed";
        /** @description Public, read-only representation of an organization (catalog face). */
        OrganizationPublic: {
            readonly id: number;
            name: string;
            readonly slug: string;
            description?: string;
            /** Format: uri */
            website?: string;
        };
        /** @description Public, read-only representation of an organization (catalog face). */
        OrganizationPublicRequest: {
            name: string;
            description?: string;
            /** Format: uri */
            website?: string;
        };
        PaginatedAPIKeyList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["APIKey"][];
        };
        PaginatedCategoryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Category"][];
        };
        PaginatedCityList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["City"][];
        };
        PaginatedDueSourceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DueSource"][];
        };
        PaginatedEventList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Event"][];
        };
        PaginatedEventObservationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["EventObservation"][];
        };
        PaginatedIngestionRunList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["IngestionRun"][];
        };
        PaginatedOrganizationPublicList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["OrganizationPublic"][];
        };
        PaginatedVenueList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Venue"][];
        };
        PatchedCategoryRequest: {
            name?: string;
        };
        PatchedEventRequest: {
            title?: string;
            description?: string;
            /** Format: date-time */
            starts_at?: string;
            /** Format: date-time */
            ends_at?: string | null;
            capacity?: number | null;
            event_type?: components["schemas"]["EventTypeEnum"];
            attendance_mode?: components["schemas"]["AttendanceModeEnum"];
            /** Format: uri */
            original_url?: string;
            original_platform?: string;
            owner_group_id?: number | null;
            category_ids?: number[];
            venue_id?: number | null;
            organization_id?: number | null;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
        };
        /**
         * @description Report an ingestion run.
         *
         *     On create, ``status`` defaults to ``running`` and ``reported_by`` is set by
         *     the view to the calling service account. The extractor later PATCHes the run
         *     to ``succeeded`` / ``failed`` with ``finished_at`` / ``events_found`` /
         *     ``error_message``.
         */
        PatchedIngestionRunRequest: {
            source?: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string | null;
            status?: components["schemas"]["IngestionRunStatusEnum"];
            events_found?: number;
            error_message?: string;
        };
        PatchedVenueRequest: {
            name?: string;
            address?: string;
            city?: string;
            capacity?: number | null;
        };
        /**
         * @description * `pending` - Pending
         *     * `accepted` - Accepted
         *     * `rejected` - Rejected
         *     * `promoted` - Promoted
         * @enum {string}
         */
        StatusF3dEnum: "pending" | "accepted" | "rejected" | "promoted";
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            username: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        Venue: {
            readonly id: number;
            name: string;
            address?: string;
            city?: string;
            readonly latitude: string;
            readonly longitude: string;
            capacity?: number | null;
        };
        VenueRequest: {
            name: string;
            address?: string;
            city?: string;
            capacity?: number | null;
        };
        _OrganizationMini: {
            readonly id: number;
            readonly name: string;
            readonly slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_api_keys_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAPIKeyList"];
                };
            };
        };
    };
    auth_api_keys_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIKeyCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["APIKeyCreateRequest"];
                "multipart/form-data": components["schemas"]["APIKeyCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyCreate"];
                };
            };
        };
    };
    auth_api_keys_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKey"];
                };
            };
        };
    };
    auth_api_keys_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryRequest"];
                "multipart/form-data": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoryRequest"];
                "multipart/form-data": components["schemas"]["CategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategoryRequest"];
                "multipart/form-data": components["schemas"]["PatchedCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    cities_list: {
        parameters: {
            query?: {
                country_code?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCityList"];
                };
            };
        };
    };
    cities_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this city. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"];
                };
            };
        };
    };
    cities_all_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["City"];
                };
            };
        };
    };
    events_list: {
        parameters: {
            query?: {
                /**
                 * @description * `physical` - Physical
                 *     * `online` - Online
                 *     * `hybrid` - Hybrid
                 */
                attendance_mode?: "hybrid" | "online" | "physical";
                category?: number;
                category__slug?: string;
                city?: string;
                /**
                 * @description * `meetup` - Meetup
                 *     * `conference` - Conference
                 *     * `workshop` - Workshop
                 *     * `social` - Social
                 *     * `other` - Other
                 */
                event_type?: "conference" | "meetup" | "other" | "social" | "workshop";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                organization?: number;
                organization_slug?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                starts_at_after?: string;
                starts_at_before?: string;
                /**
                 * @description * `draft` - Draft
                 *     * `published` - Published
                 *     * `cancelled` - Cancelled
                 *     * `archived` - Archived
                 */
                status?: "archived" | "cancelled" | "draft" | "published";
                venue?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEventList"];
                };
            };
        };
    };
    events_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRequest"];
                "multipart/form-data": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    events_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    events_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRequest"];
                "multipart/form-data": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    events_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    events_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEventRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEventRequest"];
                "multipart/form-data": components["schemas"]["PatchedEventRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    events_archive_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRequest"];
                "multipart/form-data": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    events_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRequest"];
                "multipart/form-data": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    events_publish_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRequest"];
                "multipart/form-data": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    events_revert_to_draft_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this event. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EventRequest"];
                "multipart/form-data": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
        };
    };
    ingestion_observations_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                run?: number;
                /** @description A search term. */
                search?: string;
                source?: number;
                /**
                 * @description * `pending` - Pending
                 *     * `accepted` - Accepted
                 *     * `rejected` - Rejected
                 *     * `promoted` - Promoted
                 */
                status?: "accepted" | "pending" | "promoted" | "rejected";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEventObservationList"];
                };
            };
        };
    };
    ingestion_observations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventObservationSubmitRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EventObservationSubmitRequest"];
                "multipart/form-data": components["schemas"]["EventObservationSubmitRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventObservationSubmit"];
                };
            };
        };
    };
    ingestion_observations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this event observation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventObservation"];
                };
            };
        };
    };
    ingestion_observations_bulk_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventObservation"];
                };
            };
        };
    };
    ingestion_runs_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIngestionRunList"];
                };
            };
        };
    };
    ingestion_runs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionRunRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["IngestionRunRequest"];
                "multipart/form-data": components["schemas"]["IngestionRunRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRun"];
                };
            };
        };
    };
    ingestion_runs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingestion run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRun"];
                };
            };
        };
    };
    ingestion_runs_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingestion run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionRunRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["IngestionRunRequest"];
                "multipart/form-data": components["schemas"]["IngestionRunRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRun"];
                };
            };
        };
    };
    ingestion_runs_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingestion run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingestion_runs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingestion run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedIngestionRunRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedIngestionRunRequest"];
                "multipart/form-data": components["schemas"]["PatchedIngestionRunRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRun"];
                };
            };
        };
    };
    ingestion_runs_failure_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingestion run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionRunRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["IngestionRunRequest"];
                "multipart/form-data": components["schemas"]["IngestionRunRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRun"];
                };
            };
        };
    };
    ingestion_runs_success_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ingestion run. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionRunRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["IngestionRunRequest"];
                "multipart/form-data": components["schemas"]["IngestionRunRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRun"];
                };
            };
        };
    };
    ingestion_sources_due_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDueSourceList"];
                };
            };
        };
    };
    organizations_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOrganizationPublicList"];
                };
            };
        };
    };
    organizations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationPublic"];
                };
            };
        };
    };
    organizations_events_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationPublic"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    venues_list: {
        parameters: {
            query?: {
                city?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVenueList"];
                };
            };
        };
    };
    venues_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VenueRequest"];
                "multipart/form-data": components["schemas"]["VenueRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Venue"];
                };
            };
        };
    };
    venues_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this venue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Venue"];
                };
            };
        };
    };
    venues_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this venue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VenueRequest"];
                "multipart/form-data": components["schemas"]["VenueRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Venue"];
                };
            };
        };
    };
    venues_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this venue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    venues_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this venue. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedVenueRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedVenueRequest"];
                "multipart/form-data": components["schemas"]["PatchedVenueRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Venue"];
                };
            };
        };
    };
}
