/**
 * Domain types for the terminschleuder read-only API.
 *
 * These mirror the backend serializers (`events/serializers.py`,
 * `locations/serializers.py`). When the backend's OpenAPI schema is exported
 * (see README → "Regenerating types"), `src/api/schema.ts` is generated by
 * `openapi-typescript` and the aliases below can be re-pointed at it for a
 * single source of truth. The hand-written shapes here keep the demo
 * compiling out of the box.
 */

export interface City {
  id: number;
  geoname_id: number | null;
  name: string;
  slug: string;
  country: string;
  country_code: string;
  latitude: number | null;
  longitude: number | null;
  default_radius_km: number;
  population: number | null;
  timezone: string;
}

export interface Category {
  id: number;
  name: string;
  slug: string;
}

export interface Venue {
  id: number;
  name: string;
  address: string;
  city: string;
  latitude: number | null;
  longitude: number | null;
  capacity: number | null;
}

export interface Organization {
  id: number;
  name: string;
  slug: string;
  description: string;
  website: string;
}

export interface EventSourceNested {
  id: number;
  url: string;
  platform: string;
}

export type EventObservationStatus =
  | "pending"
  | "accepted"
  | "rejected"
  | "promoted";

export interface EventObservationNested {
  id: number;
  title: string;
  starts_at: string;
  url: string;
  platform: string;
  status: EventObservationStatus;
}

export type EventStatus = "draft" | "published" | "cancelled" | "archived";
export type EventType = "meetup" | "conference" | "workshop" | "social" | "other";
export type AttendanceMode = "physical" | "online" | "hybrid";

export interface Event {
  id: number;
  title: string;
  description: string;
  starts_at: string;
  ends_at: string | null;
  /** Optional hero image — absolute URL, read-only. null when none. */
  hero_image: string | null;
  venue: Venue | null;
  organization: Organization | null;
  categories: Category[];
  capacity: number | null;
  status: EventStatus;
  event_type: EventType;
  attendance_mode: AttendanceMode;
  published_at: string | null;
  cancelled_at: string | null;
  original_url: string;
  original_platform: string;
  source: EventSourceNested | null;
  promoted_from: EventObservationNested | null;
  created_by: number | null;
  created_at: string;
  updated_at: string;
  /** Distance (km) from the proximity query point, when annotated. */
  distance: number | null;
  latitude: number | null;
  longitude: number | null;
}

export interface Paginated<T> {
  count: number;
  next: string | null;
  previous: string | null;
  results: T[];
}

/** Label/value pairs for select controls, derived from the backend choices. */
export const EVENT_TYPE_OPTIONS: { value: EventType; label: string }[] = [
  { value: "meetup", label: "Meetup" },
  { value: "conference", label: "Conference" },
  { value: "workshop", label: "Workshop" },
  { value: "social", label: "Social" },
  { value: "other", label: "Other" },
];

export const ATTENDANCE_MODE_OPTIONS: { value: AttendanceMode; label: string }[] =
  [
    { value: "physical", label: "Physical" },
    { value: "online", label: "Online" },
    { value: "hybrid", label: "Hybrid" },
  ];